name: Deploy to Github Pages

on:
  push:
    branches: [ master ]
    
jobs:
  deploy-to-github-pages:
    #Ubuntu image for now
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .Net Core 6.0 SDK
      uses: actions/setup-dotnet@2.1.0
      with:
        dotnet-version: 6.0
    
    - name: Publish .NET Core Project 
      run: dotnet publish AdafyBlazorApp.csproj -c Release -o release --nologo
      
    - name: Commit wwwroot to Github Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
